### ISSUE TITLE
Logo overlap

### ISSUE THREAD

**Issue by owenherbert** [cp3402-students/cp3402-2021-site-cp3402-project-team02#18]
### Description
Logo overlaps navigation when MetaSlider is disabled.

![Capture](https://user-images.githubusercontent.com/60369890/118336228-9795f680-b554-11eb-93c3-1f328053e740.JPG)

### Suggested fix
Only show logo when MetaSlider ID has been assigned in theme customisation settings.

### Other
@CDennien do you have any suggestions as to how we might fix this issue in another way?

**Comment by CDennien** [comment]
@owen-master alternatively we could add margins/padding into the header div when there is no MetaSlider ID assigned. This would be better practice as it allows the user to turn of the slider and have the site function correctly.

**Comment by CDennien** [comment]
'Fix Header' commit fixes issue
