### ISSUE TITLE
Navigation text wrap

### ISSUE THREAD

**Issue by owenherbert** [cp3402-students/cp3402-2021-site-cp3402-project-team02#20]
### Description
Navigation links wrap when displayed on smaller screen sizes.

![Capture](https://user-images.githubusercontent.com/60369890/118337007-30794180-b556-11eb-97e9-00835dc3f70c.JPG)

### Suggested fix
Edit the theme styles and add a no-wrap attribute to the relevant navigation class.

### Other
Hi @CDennien, is this the issue you referred to [here](https://github.com/cp3402-students/cp3402-2021-site-cp3402-project-team02/pull/17#pullrequestreview-659818324)? If so, could you handle this issue?

**Comment by CDennien** [comment]
@owen-master yep, ill get on this

**Comment by CDennien** [comment]
'Fix Header' commit fixes issue
