### ISSUE TITLE
Improve method of adding socials

### ISSUE THREAD

**Issue by owenherbert** [cp3402-students/cp3402-2021-site-cp3402-project-team02#21]
### Description
The method for adding social icons to the footer is tedious and using a menu for the process doesn't make much sense.

![Capture](https://user-images.githubusercontent.com/60369890/118338843-8354f800-b55a-11eb-9691-1398877360b8.JPG)

### Suggested fix
Add a custom menu to theme customisation that allows for an easier setup process.

### Other
N/A

**Comment by CDennien** [comment]
Latest commit nicely implements footer socials.
