### ISSUE TITLE
Logo is too big

### ISSUE THREAD

**Issue by owenherbert** [cp3402-students/cp3402-2021-site-cp3402-project-team02#27]
### Description
The logo is too big.

![Capture](https://user-images.githubusercontent.com/60369890/118355722-e96e6900-b5b4-11eb-8df2-b3a2facddc9b.JPG)

### Suggested fix
Add a maximum height css property for the logo.

### Other
@CDennien and @aidanmegee do you have any other suggested fixes?

**Comment by CDennien** [comment]
No, the suggested fix should work best.
